name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H voidence.cc >> ~/.ssh/known_hosts
        rsync -avz --delete --exclude='.env' ./ dev@voidence.cc:/var/www/voidence.cc

    - name: Run install script
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        ssh -i ~/.ssh/id_rsa dev@voidence.cc << 'EOF'
          set -e 

          cd /var/www/voidence.cc

          # Run the installer
          bash ./install.sh
        EOF